config/routes.rb
Tumaini::Application.routes.draw do
  match "remote_sessions/create(/:client_token)" => 'remote_sessions#create', :as => "remote_sessions"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  
  resources :client_apps, :except => :show
  resources :sessions, :only => [:new, :create, :destroy]
  resources :organizations, :except => :show do
    resources :users, :only => [:new, :create]
  end
  resources :users, :except => [:new, :create] do
    collection do
      get :authorize
    end
  end

  root :to => 'sessions#new'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    
    cannot :manage, Organization
    cannot :manage, ClientApp
    can :read, User, :organization_id => user.organization_id
    can :update, User, :id => user.id
    
    cannot :manage, :all if user.new_record? # guest user gets no privlages
    can :manage, :all if user.admin?
  end
end

app/models/client_app.rb
class ClientApp < ActiveRecord::Base
  include TokenGenerator
  
  attr_accessible :name, :callback_url, :app_url
  
  has_and_belongs_to_many :organizations
  has_and_belongs_to_many :users
  
  validates :name, :presence => true,
                   :uniqueness => true
  
  before_create { generate_token(:api_key) }
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :users, :dependent => :destroy
  has_and_belongs_to_many :client_apps
  
  validates :name, :presence => true,
                   :uniqueness => true
end

app/models/user.rb
class User < ActiveRecord::Base
  include TokenGenerator
  
  attr_accessible :email, :password, :password_confirmation, :client_app_ids
  
  has_secure_password
  
  belongs_to :organization
  has_and_belongs_to_many :client_apps
  
  validates_presence_of :password, :on => :create
  validates :password_confirmation, :presence => true, :on => :create
  validates :email, :presence => true,
                    :uniqueness => true,
                    :email_format => true
  
  before_create { generate_token(:auth_token) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to users_path, :alert => exception.message
  end
  
  private
  def current_user
    @current_user ||= User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  end
  
  def logged_in?
    current_user
  end

  def login_required
    cookies[:client_token] = params[:client_token] if params[:client_token]
    unless logged_in?
      redirect_to root_url, :alert => "You must be logged in to access that page."
    end
  end
  
  helper_method :current_user
end

app/controllers/client_apps_controller.rb
class ClientAppsController < ApplicationController
  before_filter :login_required
  load_and_authorize_resource
  
  def index
    
  end
  
  def new
    
  end
  
  def create
    
    if @client_app.save
      redirect_to client_apps_path, :notice => "Client application saved successfully!"
    else
      flash.now.alert = "There was a problem saving this application."
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    
    if @client_app.update_attributes(params[:client_app])
      redirect_to client_apps_path, :notice => "Client application updated successfully!"
    else
      flash.now.alert = "There was a problem updating this application."
      render 'edit'
    end
  end
  
  def destroy
    
    @client_app.destroy
    redirect_to client_apps_path, :notice => "Client application deleted."
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :login_required
  load_and_authorize_resource
  
  def index
    
  end
  
  def new
    
  end
  
  def create
    
    if @organization.save
      redirect_to organizations_path, :notice => "Organization saved successfully!"
    else
      flash.now.alert = "There was a problem creating this organization."
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    
    if @organization.update_attributes(params[:organization])
      redirect_to organizations_path, :notice => "Organization updated successfully!"
    else
      flash.now.alert = "There was a problem updating this organization."
      render 'edit'
    end
  end
  
  def destroy
    
    @organization.destroy
    redirect_to organizations_path, :notice => "Organization and all associated users deleted."
  end
end

app/controllers/remote_sessions_controller.rb
class RemoteSessionsController < ApplicationController
  before_filter :login_required
  
  def create
    client_app_id = cookies.delete(:client_token)
    client_app = current_user.client_apps.find_by_api_key(client_app_id)
    if client_app
      callback_url = client_app.callback_url + current_user.auth_token
      redirect_to callback_url
    else
      redirect_to current_user, :alert => "You are not authorized to use that application."
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to current_user if logged_in?
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      cookies.permanent[:auth_token] = user.auth_token
      if cookies[:client_token]
        redirect_to remote_sessions_path
      else
        redirect_to user, :notice => "Logged in!"
      end
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    if logged_in?
      current_user.generate_token(:auth_token) # generate a new token to log out of all sites
      current_user.save
    end
    cookies.delete(:auth_token)
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => :authorize
  load_and_authorize_resource :except => [:new, :create, :authorize]
  
  def index
    @users_by_org = @users.where("organization_id IS NOT NULL").group_by(&:organization)
  end
  
  def new
    @organization = Organization.find(params[:organization_id]) if params[:organization_id]
    @user = @organization.users.build
    authorize! :new, @user
  end
  
  def create
    @organization = Organization.find(params[:organization_id]) if params[:organization_id]
    @user = @organization.users.build(params[:user])
    authorize! :create, @user
    if @user.save
      redirect_to organizations_path, :notice => "User created successfully."
    else
      flash.now.alert = "There was an error saving the user."
      render "new"
    end
  end
  
  def show
    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end
  
  def edit

  end
  
  def update
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
    if @user.update_attributes(params[:user])
      redirect_to users_path, :notice => 'User updated successfully.'
    else
      flash.now.alert = 'There was an error updating this user.'
      render 'edit'
    end
  end
  
  def destroy
    @user.destroy
    redirect_to :back, :notice => 'User removed.'
  end
  
  def authorize
    @user = User.find_by_auth_token(params[:auth_token], :select => 'id, auth_token')
    respond_to do |format|
      if @user
        format.json { render json: @user }
      else
        format.json { render :text => "Forbidden: Invalid Token", :status => :unauthorized }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash(type)
    case type
      when :alert
        "error"
      when :error
        "error"
      when :notice
        "info"
      when :success
        "success"
      else
        type.to_s
    end
  end
end

app/helpers/client_apps_helper.rb
module ClientAppsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/remote_sessions_helper.rb
module RemoteSessionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/client_apps/_client_app.html.erb
<li>
  <%= client_app.name %>
  <small>
    <%= link_to "Edit", edit_client_app_path(client_app) %> |
    <%= link_to "Delete", client_app, :method => :delete, :confirm => "Are you sure you want to delete this client application?" %>
  </small>
</li>

app/views/client_apps/_form.html.erb
<%= simple_form_for @client_app do |f| %>
  <%= f.input :name %>
  <%= f.input :app_url %>
  <%= f.input :callback_url %>
  <div class="actions">
    <%= f.button :submit, :class => 'primary' %>
    <%= button_tag 'Reset', :type => :reset, :class => "btn" %>
    <%= link_to 'Back', :back, :class => "btn" %>
  </div>
<% end %>

app/views/client_apps/edit.html.erb
<h1>Edit <%= @client_app.name %></h1>

<%= render 'form' %>

<%= link_to "Back", client_apps_path %>

app/views/client_apps/index.html.erb
<h1>Client Applications</h1>

<%= link_to "Add Application", new_client_app_path %><br />

<ul>
  <%= render @client_apps %>
</ul>

app/views/client_apps/new.html.erb
<h1>Add Client Application</h1>

<%= simple_form_for @client_app do |f| %>
  <%= f.input :name %>
  <%= f.input :api_key %>
  <%= f.submit %>
<% end %>

<%= link_to "Back", client_apps_path %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :div, message, :class => "alert-message " + bootstrap_flash(key) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tumaini</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>  
  <div class='topbar'>
    <div class='topbar-inner'>
      <div class='container'>
        <h3><%= link_to "Tumaini", root_url %></h3>
        <ul class='nav'>
          <%= content_tag(:li, link_to("Users", users_path)) if can? :read, User %>
          <% if current_user %>
          <li class="dropdown" data-dropdown="dropdown" >
            <a href="#" class="dropdown-toggle">My Applications</a>
            <ul class="dropdown-menu">
            <% current_user.client_apps.each do |app| %>
              <%= content_tag(:li, link_to(app.name, app.app_url)) %>
            <% end %>
            </ul>
          </li>
          <% end %>
          <%= content_tag(:li, link_to("Organizations", organizations_path)) if can? :read, Organization %>
          <%= content_tag(:li, link_to("Applications", client_apps_path)) if can? :read, ClientApp %>
          <%= content_tag(:li, link_to("Logout", logout_path)) if current_user %>
        </ul>
      </div>
    </div>
  </div>
  <div class='container'>
    <%= render :partial => 'layouts/flash', :locals => {:flash => flash} %>
    <%= yield %>
  </div>
</body>
</html>

app/views/organizations/_form.html.erb
<%= simple_form_for @organization do |f| %>
  <%= f.input :name %>
  <%= f.association :client_apps, :as => :check_boxes %>
  <div class="actions">
    <%= f.button :submit, :class => 'primary' %>
    <%= button_tag 'Reset', :type => :reset, :class => "btn" %>
    <%= link_to 'Back', :back, :class => "btn" %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Edit <%= @organization.name %></h1>

<%= render 'form' %>

app/views/organizations/index.html.erb
<h1>Organizations</h1>

<%= link_to "Add Organization", new_organization_path %>

<% @organizations.each do |org| %>
  <h2><%= org.name %></h2>
  <%= link_to "Edit", edit_organization_path(org) if can? :edit, org %> |
  <%= link_to "Delete", org, :method => :delete, :confirm => "Are you sure you want to delete this organization and all associated users?" if can? :delete, org %><br />
  <p>
    <strong>Authorized Applications:</strong>
    <%= org.client_apps.map{ |app| app.name }.join(', ') %>
  </p>
  
  <ul>
    <%= render org.users %>
    <li><%= link_to "Add new #{org.name} user", new_organization_user_path(org) %></li>
  </ul>
<% end %>

app/views/organizations/new.html.erb
<h1>Add Organization</h1>

<%= render 'form' %>

app/views/remote_sessions/create.html.erb
<h1>RemoteSessions#create</h1>
<p>Find me in app/views/remote_sessions/create.html.erb</p>

app/views/users/_user.html.erb
<li>
  <%= link_to user.email, user %>
  <small>
    <%= link_to "Edit", edit_user_path(user) if can? :edit, user %>
    <%= link_to "Delete", user, :method => :delete, :confirm => "Are you sure you want to delete this user?" if can? :delete, user %>
  </small>
</li>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :email %>
  <%= f.association( :client_apps, :as => :check_boxes, :collection => @user.organization.client_apps) if @user.organization %>
  <%= f.input :password, :required => false %>
  <%= f.input :password_confirmation, :required => false, :label => "Confirm" %>
  <div class="actions">
    <%= f.button :submit, :class => 'primary' %>
    <%= button_tag 'Reset', :type => :reset, :class => "btn" %>
    <%= link_to 'Back', :back, :class => "btn" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>
<% @users_by_org.each do |org, users| %>
  <h2><%= org.name %></h2>
  <%= link_to "Edit", edit_organization_path(org) if can? :edit, org %> |
  <%= link_to "Delete", org, :method => :delete, :confirm => "Are you sure you want to delete this organization and all associated users?" if can? :delete, org %><br />
  <p>
    <strong>Authorized Applications:</strong>
    <%= org.client_apps.map{ |app| app.name }.join(', ') %>
  </p>
  <ul>
    <%= render users %>
    <li><%= link_to "Add new #{org.name} user", new_organization_user_path(org) %></li>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= simple_form_for [@organization, @user] do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.association :client_apps, :as => :check_boxes, :collection => @user.organization.client_apps %>
  <div class="actions">
    <%= f.button :submit, :class => 'primary' %>
    <%= button_tag 'Reset', :type => :reset, :class => "btn" %>
    <%= link_to 'Back', :back, :class => "btn" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Profile</h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Authorized Applications:</strong>
  <%= @user.client_apps.map{ |app| link_to( app.name, app.app_url) }.join(', ').html_safe %>
</p>

<nav>
  <%= link_to "All Users", users_path %>
  <%= link_to "Edit", edit_user_path(@user) if can? :edit, @user %>
  <%= link_to "Delete User", @user, :method => :delete, :confirm => "Are you sure you want to delete this user?" if can? :delete, @user %>
</nav>